---
kind: pipeline
name: Test (build)
type: docker

trigger:
  event:
    exclude:
    - tag

steps:
- name: Build
  image: python:3.9
  commands:
      - pip install -U -r ./requirements.txt
      - mkdocs build

---
kind: pipeline
name: Publish
type: docker

trigger:
  branch:
    - master
  event:
    exclude:
    - tag
    - pull_request

depends_on:
  - Test (build)

steps:
- name: Build Prod
  image: python:3.9
  commands:
  - pip install -U -r ./requirements.txt
  - mkdocs build

- name: Upload
  image: appleboy/drone-scp
  settings:
    host: pa425.ftp.infomaniak.com
    source: ./site
    target: sites/ofs-ofaa.yio.at/site
    strip_components: 1
    username:
        from_secret: scp_username
    password:
      from_secret: scp_password
    port: 22
    rm: true
