# This configuration file is explained in detail here:
#  https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
site_name: Open Fiber Standards

copyright: "Copyright &copy; 2022 Open Fiber Austria Association - OFAA | supported by correlate analytics gmbh + yio gmbh"

# Better provide nav by configuration (otherwise mkdocs tries to infer the structure of your documentation which might
# lead to unexpected behavior).
# I'm not sure how it works with multi-language docs.
nav:
  - "Glossar": glossar/glossar.md
  - 'Standards':
      - 'Einführung': standards/intro.md
      - standards/fep001_feb-workflow.md
      - standards/fep002_darstellung-oaid.md
      - standards/fep003_darstellung-olid.md
  - "Zentrales OAID Register":
      - index.md
      - 'Grundlagen':
          - '3-LOM': oaid_register/introduction/3lom.md
          - '4-LOM': oaid_register/introduction/4lom.md
      - 'OAID':
          - 'Open Access ID': oaid_register/oaid/oaid.md
          - 'Open Link ID': oaid_register/oaid/olid.md
          - 'FAQ': oaid_register/oaid/discussions.md
          - 'Entstehung': oaid_register/oaid/oaid_birth.md
      - 'Diskussionen':
          - oaid_register/discussions/support.md
          - oaid_register/discussions/user_stories.md
  - 'Leitfaden Inhaus-Verkabelung':
      - inhaus_verkabelung/01_einleitung.md
      - inhaus_verkabelung/02_fokus_leitfaden.md
      - inhaus_verkabelung/03_abbreviations.md
      - inhaus_verkabelung/04_rechtliche_grundlagen.md
      - inhaus_verkabelung/05_leitfaden.md
  - license.md


theme:
  name: material
  # Logo
  logo: assets/logo/logo_ofaa_squared.png
  favicon: assets/logo/ofaa_favicon.png
  # Color settings
  palette:
    primary: white
    accent: blue
  # Language
  language: de
  # The features defined now, can be seen as useful defaults
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.expand      # uncomment this line to expand all sidebar sections by default
    # - navigation.tabs        # uncomment this line to use a horizontal nav bar as well
    # - navigation.tabs.sticky # uncomment this line to make the horizontal nav bar sticky
    # - navigation.sections    # uncomment this line to disable collapsible top-level sidebar sections and show them as bold headers
    # - navigation.indexes
    - content.code.annotate
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/regular/bookmark
      link: https://ofaa.at
      name: ofaa on the Internet
    - icon: fontawesome/brands/github
      link: https://github.com/Open-Fiber-Austria/ofs
      name: ofs on github
  generator: false
  # The following example shows how to create multilanguage support
  # but that means to create two directories within your doc folder
  # There you write the german and english one for example
  #
  # Uncomment to use:
  #alternate:
  #  - name: English
  #    link: /en/
  #    lang: en
  #  - name: Deutsch
  #    link: /de/
  #    lang: de

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
      base_path:
      - includes
      auto_append:
      - abbreviations.md
  - abbr
  - attr_list
  - def_list
  - admonition
  - tables
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.tilde
  - pymdownx.caret
