name: Publish Documentation (Prod)
on:
  push:
    branches:
      - main
      - 004_FixActions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Make use of prepare action
      - name: Prepare Environment
        uses: ./.github/actions/prepare
      # Make use of build action
      - name: Build Documentation
        uses: ./.github/actions/build
      # Use the third party action for sync.
      - name: Deploy Documentation
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "ftp"
          remote-host: ${{ secrets.DEPLOY_PROD_HOST }}
          remote-port: 21
          remote-user: ${{ secrets.DEPLOY_PROD_USER }}
          remote-password: ${{ secrets.DEPLOY_PROD_PASS }}
          remote-path: "/"
          local-path: "./site"
          sync: "full"
          debug: "true"
